#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

CodeGenerator *codegen_create(const char *output_path) {
    CodeGenerator *gen = malloc(sizeof(CodeGenerator));
    if (!gen) return NULL;
    gen->fp = fopen(output_path, "w");
    if (!gen->fp) {
        free(gen);
        return NULL;
    }
    gen->indent_level = 0;
    gen->had_error = false;
    return gen;
}

void codegen_destroy(CodeGenerator *gen) {
    if (gen) {
        if (gen->fp) fclose(gen->fp);
        free(gen);
    }
}

void codegen_indent(CodeGenerator *gen) {
    for (int i = 0; i < gen->indent_level; i++) {
        fprintf(gen->fp, "  ");
    }
}

void codegen_write_line(CodeGenerator *gen, const char *fmt, ...) {
    codegen_indent(gen);
    va_list args;
    va_start(args, fmt);
    vfprintf(gen->fp, fmt, args);
    va_end(args);
    fprintf(gen->fp, "\\n");
}

void codegen_error(CodeGenerator *gen, const char *message) {
    fprintf(stderr, "Code generation error: %s\\n", message);
    gen->had_error = true;
}

int codegen_generate(ASTNode *ast, CodeGenerator *gen) {
    if (!ast || !gen) return -1;
    codegen_write_line(gen, "// Generated by Language compiler");
    codegen_write_line(gen, "#include <stdio.h>");
    codegen_write_line(gen, "#include <stdlib.h>");
    codegen_write_line(gen, "");
    codegen_write_line(gen, "int main(void) {");
    gen->indent_level++;
    codegen_write_line(gen, "// TODO: Implement code generation");
    codegen_write_line(gen, "return 0;");
    gen->indent_level--;
    codegen_write_line(gen, "}");
    return gen->had_error ? -1 : 0;
}
